name: Observer Web CI

on:
  pull_request:
    branches: [main]

env:
  elixir_version: '1.17.0'
  otp_version: '26.2.5.6'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: '${{ env.otp_version }}'
          elixir-version: '${{ env.elixir_version }}'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: |
            observer-web-${{ hashFiles('mix.lock') }}-2025-02-01
          restore-keys: |
            observer-web-

      - name: Seed fake assets
        run: mkdir -p priv/static && touch priv/static/app.css && touch priv/static/app.js
        
      - name: Install Elixir dependencies
        run: mix do deps.get, compile --warnings-as-errors

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: '${{ env.otp_version }}'
          elixir-version: '${{ env.elixir_version }}'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: |
            observer-web-${{ hashFiles('mix.lock') }}-2025-02-01
          restore-keys: |
            observer-web-

      - name: Seed fake assets
        run: mkdir -p priv/static && touch priv/static/app.css && touch priv/static/app.js

      - name: Run tests
        run: mix coveralls.html

  analysis:
    name: Static Analysis
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: '${{ env.otp_version }}'
          elixir-version: '${{ env.elixir_version }}'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            _build
            deps
          key: |
            observer-web-${{ hashFiles('mix.lock') }}-2025-02-01
          restore-keys: |
            observer-web-

      - name: Seed fake assets
        run: mkdir -p priv/static && touch priv/static/app.css && touch priv/static/app.js
        
      - name: Install Elixir dependencies
        run: mix do deps.get, compile --warnings-as-errors

      - name: Run mix deps.unlock
        run: mix deps.unlock --check-unused

      - name: Credo
        run: mix credo --strict

      - name: Ex Doc
        run: mix docs --failed

      - name: Mix Audit
        run: mix deps.audit

      - name: Mix Sobelow
        run: mix sobelow --exit --threshold medium --skip -i Config.HTTPS

      - name: Formatted
        run: mix format --check-formatted

      - name: Restore PLT cache
        uses: actions/cache@v4
        id: plt_cache
        with:
          key: plt-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('**/*.ex') }}
          restore-keys: |
            plt-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}-${{ hashFiles('**/*.ex') }}
            plt-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}-
            plt-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
            plt-${{ steps.beam.outputs.otp-version }}-
          path: priv/plts

      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true' || github.run_attempt != '1'
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer --format github
